# @Author: Simon Dahan
# @Last Modified time: 2022-01-12 14:13:45
resolution:
  ico: 6
  sub_ico: 2

data:
  data_path: ../data/{}/{}/
  task: scan_age #scan_age #birth_age
  configuration: template #template #native
  split: validation

testing:
  bs_test: 1
  gpu: 0
  path_to_ckpt: ../logs/SiT/2022-07-16-16:07:49-tiny-finetune

transformer:
  dim: 192 #192, 384, 768
  depth: 12 #12, 12, 12
  heads: 3 #3, 6, 12
  mlp_dim: 768 #768, 1536, 3072 ## 4*dim according to DeiT
  pool: 'cls'  # or 'mean'
  num_classes: 1
  num_channels: 4
  dim_head: 64 #64
  dropout: 0.0
  emb_dropout: 0.0

sub_ico_1:
    num_patches: 80 
    num_vertices: 561 

sub_ico_2:
    num_patches: 320 
    num_vertices: 153 



