# @Author: Simon Dahan
# @Last Modified time: 2022-01-12 14:13:45
resolution:
  ico: 6
  sub_ico: 2

data:
  data_path: "../data/dHCP/patches/patches_template_data/scan_age/"
  dataloader: "numpy"
  task: "scan_age"
  data: "template"

testing:
  bs: 256
  bs_test: 1
  epochs: 3000
  gpu: 1
  l1loss: false
  testing: True
  val_epoch: 25
  load_weights_ssl: False
  load_weights_imagenet: False
  save_ckpt: True
  folder: ../logs/SiT/scan_age/template/2022-05-25-10:36:24-tiny-finetune

transformer:
  dim: 192 #192, 384, 768
  depth: 12 #12, 12, 12
  heads: 3 #3, 6, 12
  mlp_dim: 768 #768, 1536, 3072 ## 4*dim according to DeiT
  pool: 'cls'  # or 'mean'
  num_classes: 1
  num_channels: 4
  dim_head: 64 #64
  dropout: 0.0
  emb_dropout: 0.0

sub_ico_0:
    num_patches: 20
    num_vertices: 2145 

sub_ico_1:
    num_patches: 80 
    num_vertices: 561 

sub_ico_2:
    num_patches: 320 
    num_vertices: 153 



