# @Author: Simon Dahan
# @Last Modified time: 2022-01-12 15:36:28
resolution:
  ico: 6
  sub_ico: 2

data:
  data_path:  /home/sd20/data/dHCP/merged_metrics/ico_6_msm/base/
  label_path: ../labels/dHCP/
  task: birth_age #scan_age #birth_age
  configuration: template #template #native
  split: train #train #validation
  channels: 4

output:
  folder: ../data/{}/{}/

sub_ico_1:
    num_patches: 80 
    num_vertices: 561 

sub_ico_2:
    num_patches: 320 
    num_vertices: 153 



