# @Author: Simon Dahan @SD3004
# @Date:   31-08-2022 01:00:00

MODEL: sit
RECONSTRUCTION: False

##################################  DATA & TASK  ##################################

mesh_resolution:
  ico_mesh: 6 #resolution of the input mesh
  ico_grid: 2 #resolution of the grid used to extract patches
  sampling: msm #sampling used for mesh resampling and patch extraction #msm or wb
  reorder: False #reorder the sequence of patches

ico_0_grid:
    num_patches: 20 
    num_vertices: 2145

ico_1_grid:
    num_patches: 80 
    num_vertices: 561 

ico_2_grid:
    num_patches: 320 
    num_vertices: 153 

ico_3_grid:
    num_patches: 1280
    num_vertices: 45
  
ico_4_grid:
    num_patches: 5120
    num_vertices: 15

ico_5_grid:
    num_patches: 20480
    num_vertices: 5

data:
  path_to_data: /home/sd20/data/
  path_to_template: /home/sd20/data/template_spheres
  path_to_workdir: /home/sd20/workspace/sMAE
  dataset: dHCP  #dHCP, HCP, UKB
  dataloader: metrics #metrics, numpy
  task: birth_age  #scan_age, birth_age, sex, handedness, income_level, fluid_intelligence, sex_msmall, scan_age_msmall,iq
  configuration: template #native, template
  masking: True # True to mask the cut. 
  hemi: half #half, full
  hemi_part: all
  normalise: sub-standardise #standardise, standardise-vertex-wise,standardise-channel-wise,False, normalise, group-standardise,sub-standardise
  modality: cortical_metrics #cortical_metrics, fMRI, memory_task
  clipping: True #True, False

logging:
  folder_to_save_model: "{}/logs/{}/{}/{}/SiT/ico_grid_{}/{}" #{dataset},{modality},{task},{grid resolution},{configuration}

###################################  MODEL  ####################################

transformer:
  dim: 192 #192, 384, 768, 96, 48
  depth: 12 #12, 12, 12
  heads: 3 #3, 6, 12
  mlp_ratio: 4 #mlp_dim: 768 #768, 1536, 3072 ## 4*dim according to DeiT
  pool: 'cls'  # 'cls' or 'mean'
  num_classes: 1
  #num_channels: 4 #cortical_metrics UKB/dHCP = 4; fMRI UKB = 490
  channels: [0,1]
  dim_head: 64 #64,32,16
  dropout: 0.0
  emb_dropout: 0.0
  use_pos_embedding: 'sin-cos' #'trainable', 'sin-cos', False
  use_class_token: True #False
  trainable_pos_emb: False #False #only for use_pos_embedding=trainable
  no_class_emb: False #to use pos emb in the class token -> False, else True
  init_weights: False #True

##################################  TRAINING  ###################################
  
training:
  LR: 0.0001
  bs: 32
  bs_val: 1
  epochs: 250
  val_epoch: 5
  log_training_epoch: 5 #default 5, fMRI 1
  gpu: 1
  loss: mse #mse, l1
  testing: True
  testing_debug: False
  init_weights: False #ssl_mae, ssl_smae, ssl_mpp, imagenet or False
  finetuning: True
  save_ckpt: True
  use_confounds: True
  use_cross_validation: False #True
  sampler: True 
  early_stopping: 300
  cv_split: [1,2,3,4,5]
  
weights: 
  #ssl_mpp: ../logs/SwinSit/pretraining/ico_grid_UKB/scan_age/2/no_augmentation/2022-07-27-16:06:05-tiny-finetune/pretrained-net-best.pt
  #ssl_mpp: ../logs/dHCP/cortical_metrics/pretraining/scan_age/SiT/ico_grid_3/template/no_augmentation/2022-09-15-09:38:26-tiny-finetune/pretrained-net-best.pt
  #ssl_mpp: ../logs/dHCP/cortical_metrics/pretraining/scan_age/mae/SiT/ico_grid_2/template/augmentation/2022-10-17-12:17:30-tiny-finetune/encoder-best.pt
  #ssl_mpp: ../logs/dHCP/cortical_metrics/pretraining/scan_age/mae/SiT/ico_grid_2/template/no_augmentation/2022-10-21-18:40:56-tiny-finetune/encoder-best.pt
  #ssl_mpp: ../logs/dHCP/cortical_metrics/pretraining/scan_age/mae/SiT/ico_grid_2/template/no_augmentation/2022-10-21-18:41:11-tiny-finetune/encoder-best.pt  #50%
  #ssl_mpp: ../logs/dHCP/cortical_metrics/pretraining/scan_age/mae/SiT/ico_grid_2/template/no_augmentation/2022-10-26-14:40:22-tiny-finetune/encoder-best.pt  #90%
  #ssl_mpp: ../logs/dHCP/cortical_metrics/pretraining/scan_age/mae/SiT/ico_grid_2/template/no_augmentation/2022-10-25-11:08:53-tiny-finetune/encoder-best.pt
  #ssl_mpp: ../logs/dHCP/cortical_metrics/pretraining/scan_age/mpp/SiT/ico_grid_2/template/no_augmentation/2021-11-16-13:11:27-tiny/pretrained-net.pt #olf ckpt mpp
  #ssl_mpp: ../logs/dHCP/cortical_metrics/pretraining/scan_age/mae/SiT/ico_grid_3/template/no_augmentation/2022-12-09-18:28:23-tiny-finetune/encoder-best.pt
  #ssl_mpp: ../logs/UKB/cortical_metrics/pretraining/scan_age/mae/SiT/ico_grid_2/template/no_augmentation/2022-10-29-17:22:01-tiny-finetune/encoder-best.pt #50% UKB  ICO2
  #ssl_mpp:  ../logs/UKB/cortical_metrics/pretraining/scan_age/mae/SiT/ico_grid_3/template/no_augmentation/2022-11-06-22:38:21-tiny-finetune/encoder-best.pt #50% UKB ICO3
  ssl_mpp: ../logs/HCP/memory_task/pretraining/iq/mae/SiT/ico_grid_3/template/no_augmentation/2022-12-11-11:02:02-tiny-finetune/encoder-best.pt
  #ssl_mpp: ../logs/HCP/memory_task/pretraining/iq/mae/SiT/ico_grid_2/template/no_augmentation/2022-10-22-23:57:33-tiny-finetune/encoder-best.pt
  #ssl_mae: ../logs/dHCP/cortical_metrics/pretraining/scan_age/mae/SiT/ico_grid_2/template/no_augmentation/2023-06-05-13:56:19-tiny-finetune/encoder-best.pt
  #ssl_mae: ../logs/dHCP/cortical_metrics/pretraining/scan_age/mae/SiT/ico_grid_2/template/no_augmentation/2023-06-05-15:59:27-tiny-finetune/encoder-best.pt
  ssl_mae: ../logs/dHCP/cortical_metrics/pretraining/scan_age/mae/SiT/ico_grid_2/template/no_augmentation/2023-06-14-10:14:29-tiny-finetune/encoder-best.pt
  ssl_smae: ../logs/dHCP/cortical_metrics/pretraining/scan_age/smae/SiT/ico_grid_2/template/no_augmentation/2023-06-14-21:02:08-tiny-finetune/encoder-best.pt
  imagenet: 'vit_tiny_patch16_224' #ViT(dim=192, depth=12, heads=3,mlp_dim=768,dim_head=64)
  #imagenet: 'vit_small_patch16_224' #ViT(dim=384, depth=12, heads=6,mlp_dim=1536,dim_head=64)
  #imagenet: 'vit_base_patch16_224' #ViT(dim=768, depth=12, heads=12,mlp_dim=3072,dim_head=64)

augmentation: # prob of augmentation techniques need to sum to 1
  prob_augmentation: 0.0  #probability of using any of the augmentation technique; 0.0 to not use any augmentation
  prob_rotation: 0.5 #use rotation
  max_abs_deg_rotation: 15
  prob_warping: 0.5 #use non-linear warping
  prob_shuffle: 0.0 #use shuffling of patches
  warp_ico: 2

##################################  OPTIMISATION  ##################################
  
optimisation:
  optimiser: SGD
  use_scheduler: False
  scheduler: CosineDecay  # CosineDecay, StepLR, ReduceLROnPlateau
  warmup: False
  nbr_step_warmup: 50
  momentum: 0.9 #default 0.
  nesterov: False

SGD:
  weight_decay: 0. #default 0.0
  momentum: 0.9 #default 0.0
  nesterov: False

Adam:
  weight_decay: 0.01  #default 0.0, 0.01

AdamW:
  weight_decay: 0.01  #default 0.01
  
StepLR: 
  stepsize: 100
  decay: 0.1

CosineDecay:
  T_max: 50  # number of iteration to go from high to low
  eta_min: 0.00001  #minimum learning rate

fMRI:
  sampling_type: chunk #False, random, regular, chunk
  num_frames: 64
  concatenate_frames: False # True, False
  average: False # True, False
  temporal_mode: False # True, False
  use_bottleneck: False # True, False
  bottleneck_dropout: 0. # 0.
